---
title: "anca_challenge"
author: "Marcin Kierczak"
date: "6/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)

threshold <- 1
file <- "~/Desktop/anca/blast_result.csv"
species_orig <- read_csv(file, col_names = c("prod","its","replicate","OTU","size","hit","perc_ident","score","family","specie"))
```

```{r}
species <- species_orig %>% 
  group_by(prod, its, specie) %>% 
  mutate(n_replicates = n_distinct(replicate)) %>%
  ungroup()
```

```knitr::kable(species)```

```{r}
product_name <- 'PROD26'
threshold <- 1
strict <- F

my_prod <- species %>% 
  filter(prod == product_name) %>% 
  complete(its = c("ITS1", "ITS2"), replicate = c("R1","R2","R3")) %>%
  mutate(OTU = str_replace(OTU, 
                           pattern = "OTU([0-9]$)", 
                           replacement = "OTU0\\1")
         ) %>% 
  group_by(prod, its, replicate, OTU, n_replicates, specie) %>%
  summarise(n_reads = sum(size)) %>%
  ungroup() %>%
  group_by(its, specie, OTU) 
  
  # get # of species per OTU
diversity <- my_prod %>%
  ungroup() %>% 
  group_by(its, OTU, replicate) %>% 
  summarise(n_species = n())
  
my_prod <- my_prod %>% left_join(diversity)
if (strict) {
  my_prod <- my_prod %>% filter(n_replicates > threshold)
}
  
if (dim(my_prod)[1] > 0) {
  sc <- scale_color_manual(values = c('tomato','slateblue'), 
                           limits=c(0, 1), 
                           labels=c('No', 'Yes')
                           )
  pl <- ggplot(my_prod, 
               mapping = aes(x = OTU, y = specie, size = log(n_reads))) +
               geom_point(data = (my_prod %>% 
                                    filter(n_replicates <= threshold & n_reads !=0)
                                  ), color='lightgrey') +
      geom_point(data=(my_prod %>% filter(n_replicates > threshold & n_reads !=0 & n_species > 1)), color='slateblue') +
      geom_point(data=(my_prod %>% filter(n_replicates > threshold & n_reads !=0 & n_species<=1)), color='red') + 
      facet_wrap(facets = ~its + replicate, ncol = 6) +
      scale_y_discrete(limits = rev(levels(as.factor(my_prod$specie)))) +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))
} else {
    pl <- NULL
}
pl
```